In [14]:
import pandas as pd
import numpy as np
from fuzzywuzzy import fuzz, process
from nltk.corpus import words
import re
import string
import time
import unidecode

outputs_dir = "/Volumes/GoogleDrive/.shortcut-targets-by-id/0B0efpUDNVRiVME9hOFNHaU1xVW8/Nutrition_BiasInScience/WebOfScience/Industry_Tagging/Outputs/"

In [20]:
final_long = pd.read_csv(f'{outputs_dir}wos_indtagged_final_long.csv')

/opt/anaconda3/envs/rao/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3062: DtypeWarning: Columns (21,23,25,29,30,37,47,48,49,50,51,52,62,63,65,68,73,74,75,80,84) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [21]:
# Establish "match type priority"
# Top 100, US, UK, Suffix

def match_type(row):
    if row['Is_Industry'] != 1:
        return ""
    elif row['Is_Industry_Top100'] == 1:
        return "Top100"
    elif row['Is_Industry_US'] == 1:
        return "US"
    elif row['Is_Industry_UK'] == 1:
        return "UK"
    elif row['Is_Industry_Suf_Company'] == 1:
        return 'SuffixCompany'
    else:
        print("Error in the industry labelling")
        raise 

final_long['Match_Type'] = final_long.apply(match_type, axis=1)

In [29]:
# Remove extra label columns 
final_long_trim = final_long.drop(final_long.columns[4:9].tolist() + final_long.columns[10:15].tolist(), axis = 1)

In [30]:
final_long_trim.head()

,Funding.Code,Abstract.Code,Food.Code,Food.Name,Is_Industry,Companies,FU_stripped_lower,FU_stripped_upper,FU,PT,...,WC,SC,GA,UT,PM,OA,HC,HP,DA,Match_Type
0,1,1,1,TI = (amaranth),0,NaN,project horticultural innovation and learning...,project Horticultural Innovation and Learning...,"project ""Horticultural Innovation and Learning...",J,...,Nutrition & Dietetics,Nutrition & Dietetics,HT2EV,NaN,WOS:000464376900006,"DOAJ Gold, Green Published",NaN,NaN,3.08664e+07,
1,2,1,1,TI = (amaranth),0,NaN,german federal ministry for economic cooperat...,German Federal Ministry for Economic Cooperat...,German Federal Ministry for Economic Cooperat...,J,...,Nutrition & Dietetics,Nutrition & Dietetics,HT2EV,NaN,WOS:000464376900006,"DOAJ Gold, Green Published",NaN,NaN,3.08664e+07,
2,3,1,1,TI = (amaranth),0,NaN,studienstiftung des deutschen volkes,Studienstiftung des Deutschen Volkes,Studienstiftung des Deutschen Volkes,J,...,Nutrition & Dietetics,Nutrition & Dietetics,HT2EV,NaN,WOS:000464376900006,"DOAJ Gold, Green Published",NaN,NaN,3.08664e+07,
3,1,2,1,TI = (amaranth),0,NaN,polish ministry of science and higher educati...,Polish Ministry of Science and Higher Educati...,Polish Ministry of Science and Higher Educatio...,J,...,Food Science & Technology,Food Science & Technology,CN8CR,NaN,WOS:000358665800006,Green Published,NaN,NaN,2.62439e+07,
4,2,2,1,TI = (amaranth),0,NaN,national science centre poland,National Science Centre Poland,"National Science Centre, Poland [DEC-2011/01/...",J,...,Food Science & Technology,Food Science & Technology,CN8CR,NaN,WOS:000358665800006,Green Published,NaN,NaN,2.62439e+07,

In [36]:
# Long to wide
final_long_sub = final_long_trim[['Funding.Code', 'Abstract.Code', 'Match_Type', 'Companies']]
final_long_sub.fillna("")
final_wide_sub = final_long_sub.set_index(['Abstract.Code', 'Funding.Code']).unstack()
final_wide_sub.head()

ValueError: Unstacked DataFrame is too big, causing int32 overflow

In [35]:
final_long_sub.head()

   Funding.Code  Abstract.Code Match_Type Companies
0             1              1                  NaN
1             2              1                  NaN
2             3              1                  NaN
3             1              2                  NaN
4             2              2                  NaN